#define OP_STRING "fuck"
#define OP_PUSH   "FUUUCK"
#define OP_FUN    "cunt"
#define OP_LOAD   "shit"
#define OP_CALL   "ass"
#define OP_DEF    "cock"
#define OP_ENDDEF "dick"
#define OP_PSTACK "twat"
#define OP_LOOP   "pussy"
#define OP_DUPE   "cooch"

#define OP_ADD "OHH"
#define OP_SUM "OOH"
#define OP_SUB "MMM"
#define OP_MUL "AHH"
#define OP_DIV "FCKMEHRDR"
